### ISSUE TITLE
Bug Report: Missing ID attribute for <ComposedBlock Type ="Table"> in AbbyyToAltoConverter

### ISSUE THREAD

**Issue by carlchan1994** [Mewel/abbyy-to-alto#1]
Missing ID attribute for <ComposedBlock Type ="Table"> in AbbyyToAltoConverter

ID attribute is a required attribute for all BlockType. This is specified at both alto-v2.0.xsd and alto-3-1.xsd.

Adding the following code at AbbyyToAltoConverter.java can solve the problem of generating invalid XML document:

Line 90:    AtomicInteger tableElementCount = new AtomicInteger(0);
Line 120:  tableBlock.setID("Table_" + tableElementCount.incrementAndGet());

**Comment by Mewel** [comment]
Added it. Thanks for the help 👍
