### ISSUE TITLE
Invalid block type Barcode

### ISSUE THREAD

**Issue by ponchofiesta** [Mewel/abbyy-to-alto#4]
Currently this library doesn't support the block type "Barcode". This is a valid block type in Finereader format. This library throws an Exception for this type. Real support may be difficult I think but it would be good to not throw exceptions for unsupported types which are valid. Maybe you could write to log for this block type?

```java
} else if (blockType.equals("Barcode")) {
  LOGGER.warn("Unsupported block type '" + blockType + "' at " + blockRect);
} else {
  throw new ConvertException("Invalid block type " + blockType + " at " + blockRect);
}
```

**Comment by Mewel** [comment]
Sounds good, I did as you suggested.
